import { test } from 'node:test';
import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { resolve } from 'node:path';
import { Marked } from 'marked';
import { sha256 } from '../scripts/agent-discovery.mjs';
import { readSnapshot } from '../scripts/library-docs.mjs';
import { publishedMarkdown } from '../scripts/published-docs.mjs';

const root = fileURLToPath(new URL('../', import.meta.url));
const read = path => readFile(resolve(root, 'dist', path.replace(/^\//, '')), 'utf8');
const parse = async path => JSON.parse(await read(path));

test('corpus retrieval returns exact published Markdown and distinct source identity for every page', async () => {
  const corpus = await parse('docs/corpus.json');
  const { manifest, pages } = await readSnapshot(resolve(root, 'content/library-docs'));
  assert.equal(corpus.schemaVersion, 1);
  assert.equal(corpus.packageVersion, manifest.packageVersion);
  assert.equal(corpus.sourceRevision, manifest.sourceRevision);
  assert.equal(corpus.sourceContentSha256, manifest.contentSha256);
  assert.equal(corpus.sourceDirty, false);
  assert.equal(corpus.publicationEditsSha256, sha256(await read('docs/publication.json')));
  assert.equal(new Set(corpus.documents.map(doc => doc.id)).size, corpus.documents.length);
  for (const doc of corpus.documents) {
    assert.equal(doc.markdown, await read(new URL(doc.markdownUrl).pathname));
    assert.equal(doc.sha256, sha256(doc.markdown));
    assert.equal(doc.sourceSha256, sha256(await read(new URL(doc.sourceUrl).pathname)));
    const html = await read(`${new URL(doc.url).pathname}index.html`);
    assert.ok(html.includes(`href="${new URL(doc.markdownUrl).pathname}"`));
    const source = pages.find(page => page.source === doc.id);
    if (source) {
      const code = markdown => {
        const blocks = [];
        const parser = new Marked();
        parser.walkTokens(parser.lexer(markdown), token => { if (token.type === 'code' || token.type === 'codespan') blocks.push(token.text); });
        return blocks;
      };
      assert.deepEqual(code(doc.markdown), code(publishedMarkdown(source)), doc.id);
    }
  }
  assert.equal(corpus.documents.filter(doc => doc.kind === 'guide').length, pages.length);
  const beta = corpus.documents.find(doc => doc.id === 'docs/beta.md');
  assert.notEqual(beta.sha256, beta.sourceSha256, 'published reading and original bytes must not share a misleading hash');
});

test('root index and task syllabus lead to resolvable version-matched resources', async () => {
  const corpus = await parse('docs/corpus.json');
  for (const path of ['llms.txt', 'docs/llms.txt', 'docs/agent-start.md', 'docs/coverage.md']) {
    const markdown = await read(path);
    assert.ok(markdown.includes(corpus.packageVersion));
    assert.ok(markdown.includes(corpus.sourceRevision));
    const parser = new Marked();
    const urls = [];
    parser.walkTokens(parser.lexer(markdown), token => { if (token.type === 'link') urls.push(new URL(token.href)); });
    for (const url of urls) {
      assert.equal(url.origin, 'https://marionettejs.com');
      await read(url.pathname + (url.pathname.endsWith('/') ? 'index.html' : ''));
    }
  }
  for (const path of ['index.html', 'why/index.html', 'thanks/index.html', 'docs/index.html', 'docs/agent-start/index.html', 'docs/coverage/index.html']) {
    assert.match(await read(path), /rel="describedby" href="\/llms.txt"/);
  }
});

test('full context and topic bundles include reading copies once with intact code bytes', async () => {
  const corpus = await parse('docs/corpus.json');
  const full = await read('llms-full.txt');
  const bundles = await Promise.all(['start', 'integrations', 'reference'].map(name => read(`docs/bundles/${name}.txt`)));
  for (const doc of corpus.documents) {
    assert.ok(full.includes(doc.markdown), doc.id);
    assert.equal(full.split(`Document: ${doc.id}\n`).length - 1, 1);
    assert.equal(bundles.filter(bundle => bundle.includes(`Document: ${doc.id}\n`)).length, 1, doc.id);
  }
});

test('artifact manifest verifies generated bytes and coverage reports its real limits', async () => {
  const manifest = await parse('docs/artifacts.json');
  assert.equal(new Set(manifest.artifacts.map(item => item.path)).size, manifest.artifacts.length);
  assert.ok(manifest.artifacts.some(item => item.path === '/docs/corpus.json'));
  assert.ok(!manifest.artifacts.some(item => item.path === '/docs/artifacts.json'));
  for (const item of manifest.artifacts) {
    const bytes = await readFile(resolve(root, 'dist', `.${item.path}`));
    assert.equal(item.sha256, sha256(bytes), item.path);
    assert.equal(item.bytes, bytes.length, item.path);
  }
  const coverage = await parse('docs/coverage.json');
  assert.equal(coverage.snapshotPages, coverage.publishedPages);
  assert.equal(coverage.corpusDocuments, coverage.publishedPages + coverage.diagnostics + 1);
  assert.ok(coverage.checkedLocalLinks > 500);
  assert.deepEqual(coverage.unresolvedLinks, []);
  assert.ok(coverage.limitations.some(value => value.includes('not every API')));
});

test('production headers stay within Cloudflare limits and expose safe retrieval types', async () => {
  const headers = await read('_headers');
  assert.ok(headers.split('\n').filter(line => /^(?:\/|https:)/.test(line)).length <= 100);
  assert.ok(headers.split('\n').every(line => line.length <= 2000));
  assert.ok(headers.includes('/docs/:page.md\n  Content-Type: text/markdown; charset=utf-8'));
  assert.ok(headers.includes('/errors/:code.md\n  Content-Type: text/markdown; charset=utf-8'));
  assert.ok(headers.includes('/docs/:resource.json\n  Content-Type: application/json; charset=utf-8'));
  assert.ok(headers.includes('/llms-full.txt\n  Content-Type: text/plain; charset=utf-8'));
  assert.ok(headers.includes('/docs/:page/\n  Link: <https://marionettejs.com/docs/:page.md>'));
});


test('llms indexes use level-two sections containing Markdown file lists', async () => {
  for (const path of ['llms.txt', 'docs/llms.txt']) {
    const markdown = await read(path);
    assert.doesNotMatch(markdown, /^### /m);
    for (const section of markdown.split(/^## /m).slice(1)) assert.match(section, /^- \[.+?\]\(https:\/\/marionettejs\.com\//m);
  }
  assert.ok((await read('_headers')).includes('/docs/*\n  Link: <https://marionettejs.com/docs/llms.txt>; rel="describedby"'));
});
