import assert from 'node:assert/strict';
import { execFileSync } from 'node:child_process';
import { cp, mkdir, mkdtemp, readFile, rm, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { test } from 'node:test';

test('supplement import reads committed files and preserves the published beta snapshot', async t => {
  const directory = await mkdtemp(join(tmpdir(), 'marionette-guide-import-'));
  t.after(() => rm(directory, { recursive: true, force: true }));
  const source = join(directory, 'library');
  const website = join(directory, 'website');
  await mkdir(join(source, 'docs'), { recursive: true });
  await mkdir(join(website, 'scripts'), { recursive: true });
  await mkdir(join(website, 'content/library-docs'), { recursive: true });
  await writeFile(join(website, 'content/library-docs/manifest.json'), 'published');
  await cp(new URL('../scripts/import-development-docs.mjs', import.meta.url), join(website, 'scripts/import-development-docs.mjs'));
  await writeFile(join(source, 'package.json'), JSON.stringify({ version: '5.0.0-beta.1' }));
  for (const name of ['development', 'troubleshooting']) await writeFile(join(source, `docs/${name}.md`), `# ${name}\n`);
  const git = args => execFileSync('git', args, { cwd: source, encoding: 'utf8' }).trim();
  git(['init', '-q']); git(['add', '.']);
  git(['-c', 'user.name=Guide test', '-c', 'user.email=guide@example.invalid', '-c', 'core.hooksPath=/dev/null', 'commit', '-qm', 'guides']);
  const commit = git(['rev-parse', 'HEAD']);
  await writeFile(join(source, 'docs/development.md'), '# Uncommitted changes\n');
  execFileSync(process.execPath, [join(website, 'scripts/import-development-docs.mjs'), source]);
  const manifest = JSON.parse(await readFile(join(website, 'content/development-docs/manifest.json')));
  assert.equal(manifest.sourceRevision, commit);
  assert.equal(manifest.sourceDirty, false);
  assert.equal(await readFile(join(website, 'content/development-docs/docs/development.md'), 'utf8'), '# development\n');
  assert.equal(await readFile(join(website, 'content/library-docs/manifest.json'), 'utf8'), 'published');
});
