import { listRecipes } from '../site/assets/playground-recipes.js';
const pixelIcon = paths => `<svg viewBox="0 0 64 48" aria-hidden="true" shape-rendering="crispEdges">${paths}</svg>`;
const chooser = {
  'list-detail': { icon: pixelIcon('<path fill="currentColor" d="M14 4h36v40H14z"/><path fill="#111415" d="M18 8h28v32H18z"/><path fill="currentColor" d="M22 12h4v4h-4zm8 0h12v4H30zM22 22h4v4h-4zm8 0h12v4H30zM22 32h4v4h-4zm8 0h12v4H30z"/>'), name: 'TodoMVC', hint: 'Changing lists · independent Views' },
  'owned-widget': { icon: pixelIcon('<path fill="currentColor" d="M46 0h4v4h-4zm-4 4h4v4h-4zm-4 4h4v4h-4zM10 12h44v32H10z"/><path fill="#111415" d="M14 16h36v8H14zm0 12h20v12H14zm26 0h8v8h-8z"/><path fill="currentColor" d="M18 18h20v4H18zm0 12h4v8h-4zm8 0h4v8h-4z"/>'), name: 'Radio Ghostbusters', hint: 'External widgets · cleanup' },
  'mission-control': { icon: pixelIcon('<path fill="currentColor" d="M28 0h8v4h-8zm-4 4h16v8H24zm-4 8h24v20H20zm-4 12h4v16h-4zm-4 8h4v12h-4zm32-8h4v16h-4zm4 8h4v12h-4zM24 36h4v8h-4zm12 0h4v8h-4zm-8 4h8v8h-8z"/><path fill="#111415" d="M28 12h8v8h-8z"/>'), name: 'Cheese Patrol', hint: 'Readiness · cancelling unfinished work' },
};
export const examples = {
  title: 'Interactive demos — Marionette 5',
  description: 'Try small Marionette apps, follow their source, and choose the next change for your agent. Lists, widget cleanup, cancellation, and Application readiness.',
  active: 'examples',
  body: `<section class="examples-page" id="examples">
    <header class="examples-intro"><div><p class="eyebrow">THE DEMONSTRATION PROGRAMME</p><h1>Pull a string.<br><em>Follow it back.</em></h1></div><p>You decide what the app should do. Your agent can learn the APIs. These small apps let you try the behavior and follow the code behind it.</p></header>
    <ol class="example-journey" aria-label="Explore a demo"><li><strong>Try the behavior</strong><span>Add a todo, replace a radio, or interrupt a launch.</span></li><li><strong>Follow the source</strong><span>The reading trail takes you to the method behind the action.</span></li><li><strong>Direct the next change</strong><span>Download a demo for your agent, or edit and run it here.</span></li></ol>
    <section class="example-chooser" id="example-chooser" aria-label="Choose a demo"><div class="example-cards">${listRecipes().map((recipe, index) => `<button id="${recipe.id}" data-example-id="${recipe.id}" class="demo-card" type="button" aria-pressed="false"><span class="example-number" aria-hidden="true">0${index + 1}</span><span class="example-card-copy"><strong>${chooser[recipe.id].name}</strong><small>${chooser[recipe.id].hint}</small></span><span class="example-icon" aria-hidden="true">${chooser[recipe.id].icon}</span></button>`).join('')}</div></section>
    <section class="example-workbench" aria-label="Interactive example">
      <header class="example-heading"><div><p class="eyebrow">ON THE BENCH</p><h2 id="example-title">TodoMVC, one View at a time</h2></div><div><button data-example-restart type="button">Reset example</button><button data-example-download type="button">Download project ↓</button><button data-example-codepen form="example-codepen" type="submit" disabled>View on CodePen ↗</button></div></header>
      <p id="example-status" role="status">Preparing the example…</p><pre id="example-errors" role="alert" hidden></pre>
      <div class="example-preview" aria-label="Running example"></div>
      <section class="example-source" aria-labelledby="example-source-title"><h3 id="example-source-title">Follow the strings</h3><p>Pick a step below to jump to the code behind an action. You can follow which part handles it without memorizing every API. Edit the source and run your changes here, or download the project for your agent.</p><nav id="example-reading-guide" aria-label="Source reading trail"></nav><p id="example-reading-location" role="status"></p><div class="example-source-tabs" role="tablist" aria-label="Example source files"><button type="button" role="tab" id="example-js-tab" aria-selected="true" aria-controls="example-js-panel">app.js</button><button type="button" role="tab" id="example-css-tab" aria-selected="false" aria-controls="example-css-panel" tabindex="-1">style.css</button><button type="button" role="tab" id="example-lesson-tab" aria-selected="false" aria-controls="example-lesson-panel" tabindex="-1">lesson.js</button></div><div role="tabpanel" id="example-js-panel" aria-labelledby="example-js-tab"><label for="example-code" class="sr-only">Example JavaScript</label><textarea id="example-code" spellcheck="false" maxlength="60000"></textarea></div><div role="tabpanel" id="example-css-panel" aria-labelledby="example-css-tab" hidden><label for="example-css" class="sr-only">Example CSS</label><textarea id="example-css" spellcheck="false" maxlength="20000"></textarea></div><div role="tabpanel" id="example-lesson-panel" aria-labelledby="example-lesson-tab" hidden><label for="example-lesson" class="sr-only">Lesson JavaScript</label><textarea id="example-lesson" spellcheck="false" maxlength="60000"></textarea></div><button data-example-run type="button">Run my changes ↗</button></section>
      <p class="example-export-note">CodePen runs the current module project. Download includes its source files, HTML, CSS, and runtime. Your Backstage app is separate.</p><nav id="example-docs" aria-label="Related documentation"></nav>
      <form id="example-codepen" action="https://codepen.io/pen/define" method="POST" target="_blank" rel="noopener noreferrer" hidden><input name="data" type="hidden"></form>
    </section>

    <section class="example-next" aria-labelledby="example-next-title"><div><p class="eyebrow">YOUR NEXT DIRECTION</p><h2 id="example-next-title">Same app.<br><em>New request.</em></h2></div><div><p>Select TodoMVC, then download it and give your agent a small change to make:</p><blockquote>“Add a count of completed todos beside the filters. Keep my notes intact while I add, complete, and filter todos.”</blockquote><p>Give it the <a href="/docs/agent-start/">agent docs</a>, then check the behavior and ask it to explain the changed code. This is a suggested next exercise; the demos above run locally in your browser.</p><p>For a fuller application, the <a href="/docs/records/">Records guide</a> connects loading, selection, retry, and closing a feature. Its source gives your agent a practical example to work from.</p></div></section>

    <noscript><p>The interactive examples need JavaScript. Read the <a href="/docs/api/region/">Region guide</a> or <a href="/docs/api/application/">Application guide</a>.</p></noscript>
  </section>`
};

export const demosInvitation = `
<section class="home-demos" id="demos" aria-labelledby="home-demos-title">
  <div class="home-demos-copy"><p class="eyebrow">PULL A FEW STRINGS</p><h2 id="home-demos-title">Try the app.<br>Direct the <em>next act.</em></h2><p>Add a todo, retire a radio, or cancel a launch. Follow the source, then download a demo and give your agent a change to make.</p><a class="text-link" href="/demos/">Explore the demos →</a></div>
  <div class="home-demo-cards">${listRecipes().map(recipe => `<a class="demo-card" href="/demos/#${recipe.id}"><span class="demo-select-label" aria-hidden="true">SELECT ↗</span><span class="example-icon" aria-hidden="true">${chooser[recipe.id].icon}</span><span class="example-card-copy"><strong>${chooser[recipe.id].name}</strong><small>${chooser[recipe.id].hint}</small></span></a>`).join('')}</div>
</section>`;
