import { invitation } from './playground.mjs';
import { adoptionInvitation } from './adoption.mjs';

const demo = `<section class="demo application-demo" id="demo" aria-labelledby="demo-title">
  <div class="demo-heading"><span class="eyebrow" id="demo-title">APPLICATION / PREVIEW</span><span class="live-indicator">LIVE LIBRARY</span></div>
  <div id="application-slot"><p class="empty-region">Enable JavaScript to explore a small Marionette application.</p></div>
  <p class="demo-status" id="demo-status" role="status">One Application. A screen with independently owned parts.</p>
</section>`;

export const home = {title:'Marionette 5 — JavaScript library for agent-led development',description:'Build JavaScript applications with explicit structure, ownership, and lifecycles. Tuned for coding agents, with data and rendering tools you choose.',active:'home',body:`
<div class="opening-act"><svg class="opening-thread" aria-hidden="true"><path/></svg>
<section class="night-hero">
  <div class="hero-grid" aria-hidden="true"></div>
  <div class="night-copy"><p class="eyebrow"><span class="signal-dot"></span> MARIONETTE 5.0</p><h1>Pull a few<br><em>strings.</em></h1><p class="night-intro">A JavaScript library for interfaces,<br>tuned for agent-led development.</p><div class="night-actions"><a class="button" href="/why/">Explore Marionette <span aria-hidden="true">↗</span></a><a class="text-link" href="/docs/regions/">Read the docs →</a></div></div>
  <div class="rig" data-rig>
    <div class="rig-decoration" aria-hidden="true"><div class="rig-control"><span class="yoke-pin pin-left"></span><img src="/assets/mark.svg" width="68" height="70" alt=""><span class="yoke-pin pin-right"></span></div><svg class="rig-strings" viewBox="0 0 560 96" preserveAspectRatio="none"><path d="M84 0 V96 M476 0 V96"/><circle cx="84" cy="94" r="3"/><circle cx="476" cy="94" r="3"/></svg><span class="rig-annotation">A PLACE FOR EVERYTHING.</span></div>
    ${demo}
    <p class="rig-caption">A little application. <span>Pick a piece of work.</span></p>
  </div>
  <div class="hero-bottom" aria-hidden="true"></div>
</section>
${invitation}
</div>
<section class="lifecycle-story" id="lifecycle" aria-labelledby="story-title" data-story>
 <div class="story-layout">
  <div class="story-copy"><p class="eyebrow">01 / A LIFECYCLE, ILLUSTRATED</p><h2 id="story-title">A good entrance.<br><em>A clean exit.</em></h2><p>A Region stays. Its Views come and go.<br>Follow one change from entrance to exit.</p><div class="phase-controls" aria-label="Explore lifecycle stages"><button type="button" data-phase="0" aria-pressed="true" disabled>01 <span>Show</span></button><button type="button" data-phase="1" aria-pressed="false" disabled>02 <span>Replace</span></button><button type="button" data-phase="2" aria-pressed="false" disabled>03 <span>Empty</span></button></div><div class="sequence-actions"><button type="button" class="sequence-play" aria-label="Play the lifecycle" disabled>Play the lifecycle <span aria-hidden="true">▷</span></button><span>Or choose a step above.</span></div><code class="story-command" id="story-command">region.show(notes);</code><p class="phase-description" id="phase-description">The Region renders and attaches its current View.</p><output class="lifecycle-events" id="lifecycle-events" aria-label="Observed lifecycle events" hidden></output><a class="text-link" href="/docs/regions/">Read the actual contract →</a></div>
  <div class="ownership-scene" data-phase="0" role="img" aria-label="Lifecycle illustration: a Region displays NotesView.">
   <div class="scene-floor"></div><div class="owner-node"><span class="signal-dot"></span> Region <code>preview</code></div><div class="ownership-thread"></div>
   <div class="lifecycle-slot"><div class="diagram-view old-view"><span>VIEW / 01</span><strong>NotesView</strong><div class="skeleton"><i></i><i></i><i></i></div><small>rendered → attached</small></div></div>
   <div class="empty-boundary"><span>Nothing here.</span><small>The Region is ready for another View.</small></div><div class="exit-receipt"><span>✓</span> <span data-receipt>Previous View destroyed</span></div><span class="scene-label">OWNERSHIP IS A RELATIONSHIP.<br>LEAVING IS PART OF IT.</span>
  </div>
 </div>
</section>
<section class="ownership" id="ownership" aria-labelledby="structure-title">
 <div class="structure-copy"><p class="eyebrow">02 / A PLACE FOR THE WHOLE APPLICATION</p><h2 id="structure-title">More than a View.<br><span>Thankfully.</span></h2><p>Give features their own lifecycle.<br>Give the moving parts a place to belong.</p><a class="text-link" href="/why/">Why that might matter now →</a></div>
 <figure class="structure-map" aria-label="Example application structure: an Application owns a child Application, which displays a screen View. The screen has list and detail Regions. A CollectionView owns the list's row Views. A Behavior adds reusable interaction to the screen.">
  <div class="structure-app"><div class="structure-heading"><span class="signal-dot"></span><strong>Application</strong><small>start → stop</small></div>
   <div class="structure-feature"><div class="structure-feature-heading"><strong>Workspace</strong><span>child Application</span></div>
    <div class="structure-screen"><div class="structure-screen-heading"><strong>View</strong><span>the screen</span></div>
     <div class="structure-regions">
      <div class="structure-region"><span class="structure-region-label">REGION <b>list</b></span><div class="structure-collection"><strong>CollectionView</strong><div class="structure-rows" aria-hidden="true"><span>View <i></i></span><span>View <i></i></span><span>View <i></i></span></div></div></div>
      <div class="structure-region"><span class="structure-region-label">REGION <b>detail</b></span><div class="structure-detail"><strong>View</strong><span aria-hidden="true">A closer look.</span><i aria-hidden="true"></i><i aria-hidden="true"></i></div></div>
     </div>
     <div class="structure-behavior"><span aria-hidden="true">↳</span><strong>Behavior</strong><span>shared interaction</span></div>
    </div>
   </div>
  </div>
  <figcaption><span>State + events</span><span>Keep the pieces talking.</span></figcaption>
 </figure>
</section>
<section class="night-honesty"><p class="eyebrow">03 / REASONABLE SUPERVISION</p><h2>We’re optimistic<br>about agents.<br><em>We’ve also read<br>the diffs.</em></h2><div><p>An agent can write the next feature. You should be able to follow what changed.</p><p>Marionette makes ownership explicit, gives changes a place to belong, and keeps the structure visible to whoever reads the diff.</p><a class="text-link" href="/why/#evidence">See the structure at work →</a></div><span class="honesty-mark" aria-hidden="true">*</span></section>
<section class="night-closing"><p class="eyebrow">YES, THAT MARIONETTE.</p><h2>A familiar name.<br><span>Still pulling strings.</span></h2><p>Choose your data and rendering tools.<br>Marionette gives the application its structure.</p><a class="button" href="/why/">Explore Marionette 5.0 <span aria-hidden="true">↗</span></a></section>
<section class="home-support" aria-labelledby="home-support-title">
 <div><p class="eyebrow">OPEN SOURCE / HUMAN MAINTAINED</p><h2 id="home-support-title">A little help behind the strings.</h2><p>Support the maintenance, docs, and releases on Patreon.<br>Or put your very specific taste in JavaScript on a T-shirt.</p><a class="text-link" href="/thanks/">Meet the people and tools behind Marionette →</a></div>
 <div class="support-actions"><a class="button" href="https://www.patreon.com/marionettejs">Support on Patreon <span aria-hidden="true">↗</span></a><a class="text-link" href="https://store.marionettejs.com/">Browse the merch store <span aria-hidden="true">↗</span></a></div>
</section>`};

export const why={title:'Why Marionette 5? Application structure for coding agents',description:'Evaluate Marionette for your JavaScript project: application structure, agent-led development, flexible integrations, and the tradeoffs that matter.',active:'why',body:`
<section class="article-heading"><p class="eyebrow">THE ADOPTION QUESTION</p><h1>Should I use<br><em>Marionette?</em></h1><p>When agents write more of your interface, give them a structure you can follow.</p></section>${adoptionInvitation}
<div class="article-layout"><aside class="article-nav" aria-label="On this page"><p class="eyebrow">ON THIS PAGE</p><a href="#agents">Tuned for agents</a><a href="#fit">The whole application</a><a href="#integrations">Your choice of tools</a><a href="#community">The community question</a><a href="#slop">The slop question</a><a href="#evidence">See it at work</a><a href="#next-step">Try a feature</a></aside>
<article class="prose">
<section id="agents"><p class="eyebrow">01 / GIVE YOUR AGENT A BETTER START</p><h2>Help it find the right approach.</h2><p>Marionette is tuned to help agents find the right approach for the task, with consistent APIs, explicit contracts, and guidance designed for how they work.</p><p>A useful library gives an agent more than methods to call. It gives familiar problems recognizable solutions:</p><ul><li><strong>Change part of a screen.</strong> A named Region identifies where the new View belongs and handles replacing the old one.</li><li><strong>Keep each instance independent.</strong> View-local state has an explicit home, including the objects and collections inside it.</li><li><strong>Check that a change is complete.</strong> Public lifecycle methods let the agent verify that a View was attached, replaced, or destroyed.</li></ul><p>Those patterns give the agent a route from the request to the implementation—and give you something specific to review.</p></section>
<section id="fit"><p class="eyebrow">02 / A PLACE FOR THE WHOLE APPLICATION</p><h2>Build features that fit together.</h2><p>Applications manage feature lifecycles. Views compose screens through named Regions. CollectionViews manage repeated pieces. Behaviors share interaction logic. State and events connect the parts.</p><p>A feature can own its screen and the work that starts and stops with it. The next feature gets the same vocabulary, without having to recreate the first feature’s internal decisions.</p><div class="fit-grid"><div><h3>A good fit</h3><ul><li>Interactive applications with nested, changing screens.</li><li>Features with their own state, events, and cleanup.</li><li>Teams using agents to implement code that people will maintain.</li></ul></div><div><h3>Start with your requirements</h3><ul><li>The experience you need to build.</li><li>Required components, integrations, and delivery constraints.</li><li>Who will implement, review, and support the application.</li></ul></div></div></section>
<section id="integrations"><p class="eyebrow">03 / BRING YOUR TOOLS</p><h2>Your data. Your rendering.<br>Your application.</h2><p>Marionette separates application structure from data, state, DOM, and rendering integrations. Choose how your application gets its data and produces its interface, then connect those choices through explicit integration APIs.</p><p>For a new project, that means choosing the tools that suit the work. For an existing application, it means evaluating how Marionette can fit alongside the tools you already use.</p><p>Check the integrations your project needs, including any framework-specific components. An integration point gives you a defined way to connect a tool; a ready-made adapter is a separate question.</p></section>
<section id="community"><p class="eyebrow">04 / MORE THAN A STAR COUNT</p><h2>What will help your team build?</h2><p>Framework familiarity is useful. So are engineers who understand the application, agents that can find the right pattern, and reviewers who know what to test.</p><p>A large archive can hold years of conflicting advice. The answer may be stuck in 2013, but your agent is delighted to report that it has the most votes.</p><p>As agents do more of the implementation, the quality of the guidance they find deserves more weight in your choice of library. So do the maintainers, integrations, and experienced people your project will rely on.</p><blockquote>Your next contributor might be an agent.<br>The next reviewer still needs to follow the change.</blockquote></section>
<section id="slop"><p class="eyebrow">05 / AN ENTIRELY FAIR QUESTION</p><h2>Will this make more AI slop?</h2><p>The agent will still have ideas. Some of them will even be good.</p><p>A consistent implementation makes those ideas easier to inspect and revise. You can try the interaction, question the behavior, and ask for a change in a specific part of the application.</p><p>You still decide whether it solves the right problem. Marionette helps make the next change manageable.</p></section>
<section id="evidence"><p class="eyebrow">06 / FOLLOW A REAL CHANGE</p><h2>See what moves.<br>And what stays put.</h2><p>Choose an item in the homepage application. Its detail View is replaced and the previous one is destroyed. The screen and list keep their identities. That is a real Marionette Application doing the work.</p><p>Then bring your agent to the workshop. Have it build something for you, try the result, and ask what it found useful—or awkward—along the way.</p><a class="text-link" href="/#demo">Explore the running application →</a></section>
<section id="next-step"><p class="eyebrow">07 / MAKE IT CONCRETE</p><h2>Start with something you need.</h2><p>Choose one useful feature: the first screen of a new product, or a part of an existing application. Include an interaction, a data or state change, and a way to check its behavior.</p><p>Use that feature to judge how Marionette fits your tools, how your agent works with it, and how easily you can understand the result.</p><a class="button" href="/docs/regions/">Start with Views and Regions <span aria-hidden="true">→</span></a></section>
</article></div>`};

export const docs={title:'Views and Regions — Marionette 5 documentation',description:'Learn how Marionette Views and Regions compose JavaScript interfaces. Try live examples of rendering, View replacement, lifecycle events, and cleanup.',active:'docs',body:`
<div class="docs-layout"><aside class="docs-nav"><a class="docs-home" href="/docs/regions/">THE DOCUMENTATION <span>↗</span></a><p class="eyebrow">START WITH STRUCTURE</p><a aria-current="page" href="/docs/regions/">Views &amp; Regions</a><a href="#show">Show a View</a><a href="#replace">Replace it</a><a href="#cleanup">Clean up</a><a href="#source">Check the source</a><div class="docs-note"><span class="eyebrow">MARIONETTE 5.0</span><p>The same lifecycle contract used by the running example.</p><a href="/reference/region.md">Full reference · Markdown ↗</a></div></aside><article class="prose docs-prose"><div class="docs-breadcrumb">LEARN / APPLICATION STRUCTURE</div><h1>A View.<br><em>A place for it.</em></h1><p class="lead">Views own a piece of interface. Regions manage where a View is displayed and what happens when it is replaced.</p><p>Think of a Region as a named place in your application. Showing a View there renders and attaches it. Showing a different View replaces and destroys the previous one.</p><div class="doc-diagram" aria-label="A Region displays one current View"><span>REGION <strong>preview</strong></span><span aria-hidden="true">→</span><span>VIEW <strong>NotesView</strong></span></div><section id="show"><h2>Show a View</h2><p>Create a Region for an existing element. Define a small View, then ask the Region to show it.</p><pre><code><span class="code-keyword">import</span> { View, Region } <span class="code-keyword">from</span> <span class="code-string">'marionette'</span>;

<span class="code-keyword">const</span> NotesView = View.extend({
  template: () =&gt; <span class="code-string">'&lt;h2&gt;A place for your notes.&lt;/h2&gt;'</span>
});

<span class="code-keyword">const</span> region = <span class="code-keyword">new</span> Region({ el: <span class="code-string">'#preview'</span> });
region.show(<span class="code-keyword">new</span> NotesView());</code></pre><p><code>region.hasView()</code> now returns <code>true</code>. Its public <code>currentView</code> property identifies the displayed View.</p><p class="callout">The Region renders the View. You do not need to render it first.</p></section><section id="replace"><h2>Replace it</h2><p>Show a different View in the same Region. The Region destroys the current View before displaying the replacement.</p><pre><code><span class="code-keyword">const</span> previous = region.currentView;
region.show(<span class="code-keyword">new</span> NotesView());

previous.isDestroyed(); <span class="code-comment">// true</span>
region.hasView();       <span class="code-comment">// true</span></code></pre><p>The Region remains available. Its previous View does not.</p></section><section id="cleanup"><h2>Leaving is part of the lifecycle.</h2><p><code>region.empty()</code> destroys the current View and leaves the Region empty. Use a View’s destruction lifecycle for resources that your application creates and owns.</p><pre><code>region.empty();
region.hasView(); <span class="code-comment">// false</span></code></pre><p>A lifecycle hook is a place to release your resources; it does not automatically clean up every arbitrary timer or external subscription you create.</p><a class="button" href="/#lifecycle">Explore replacement and cleanup <span aria-hidden="true">↗</span></a></section><section id="source"><h2>Know which version you’re reading.</h2><p>This focused guide explains the lifecycle illustrated on the homepage. The full Region reference is also available as Markdown.</p><ul><li><a href="/reference/region.md">Region reference · Markdown</a></li><li><a href="/reference/provenance.json">Example runtime source</a></li><li><a href="/llms.txt">Compact agent entry point</a></li><li><a href="https://github.com/marionettejs/marionette/blob/8c8720317cfd59631335b9bc2d75269172b3db7f/docs/marionette.region.md">Pinned source on GitHub ↗</a></li></ul><p>The examples run against the bundled Marionette runtime. The source notes identify the exact build used by this site.</p></section></article><aside class="docs-margin"><span class="eyebrow">THE SMALL PRINT</span><p>Predictable doesn’t have to mean complicated.</p><a href="/why/">Back to the bigger idea →</a></aside></div>`};
