export const invitation = `
<section class="agent-invitation" id="agent-invitation" aria-labelledby="agent-invitation-title">
 <div class="invitation-thread" aria-hidden="true"><span>✳</span></div>
 <div><p class="eyebrow">A SMALL DETOUR</p><h2 id="agent-invitation-title">Brought an agent?</h2><p>Click <strong>Copy prompt</strong>, then paste it into your agent’s chat. It’ll use this site to build a small app just for you, while you watch.</p><p class="invitation-aside">Your agent needs a browser it can control and you can see.<br>We’re curious what it makes of you. In a normal way.</p></div>
 <div class="invitation-action"><button type="button" class="button" data-agent-copy disabled>Copy prompt <span aria-hidden="true">↗</span></button><p id="invitation-status" role="status">Already here with your agent? Ask it to try the interaction.</p><details id="prompt-details"><summary>Read the prompt</summary><label for="agent-invitation-prompt">Give this to your agent</label><textarea id="agent-invitation-prompt" readonly rows="5">Visit this website, open the agent workshop, and read its instructions there to try the interaction with me. Use what you already know about me to make something recognizably personal. Use a browser preview I can see. If you can’t, say so; don’t create files, install anything, or start a local project.</textarea><a href="#playground" data-agent-workshop>Open the agent workshop <span aria-hidden="true">→</span></a></details><a class="invitation-human" data-playground-human href="#playground" hidden>No agent, but I wanna play <span aria-hidden="true">→</span></a><noscript><p>Copy the text above with this page’s address. The workshop needs JavaScript.</p></noscript></div>
</section>`;

export const workshop = `
<dialog id="playground" class="workshop" aria-labelledby="workshop-title" aria-describedby="workshop-description" data-state="idle">
 <div class="workshop-reveal" aria-hidden="true"><span class="reveal-string"></span><div><img src="/assets/mark.svg" width="72" height="76" alt=""><p>Oh.<br>You brought <em>help.</em></p><small>LET’S GIVE IT SOMETHING TO DO.</small></div></div>
 <header class="workshop-header"><a class="workshop-brand" href="#workshop-instructions" data-open-instructions aria-label="Read agent instructions"><img src="/assets/mark.svg" width="32" height="34" alt=""><span>MARIONETTE <span>/ BACKSTAGE</span></span></a><a class="workshop-examples-link" href="/demos/" target="_blank" rel="noopener">Demos ↗</a><button type="button" data-workshop-close>Back to the site <span aria-hidden="true">×</span></button></header>
 <details class="workshop-instructions" id="workshop-instructions"><summary>Agent instructions</summary><pre tabindex="0" aria-label="Full agent instructions"><!-- workshop-brief --></pre></details>
 <div class="workshop-intro"><div><p class="eyebrow">WELL, HELLO AGAIN.</p><h2 id="workshop-title">A little something <br><em>for you.</em></h2></div><p id="workshop-description">Your agent brings the idea.<br>Marionette gives it a place to live.<br><span>You get to see the whole thing.</span></p><span class="workshop-spool" aria-hidden="true">✳</span></div>
 <section class="workshop-process" aria-labelledby="process-title"><p id="process-title">FROM YOUR AGENT<span>IDEA → BUILD → TRY</span></p><ol id="workshop-notes" role="log" aria-live="polite" aria-label="Agent build notes"><li><span>This is where your agent can explain its choices and show its progress. No mysterious loading bar required.</span></li></ol></section>
 <div class="workshop-toolbar"><label for="app-title">THE APP<input id="app-title" maxlength="100" type="text" autocomplete="off" spellcheck="false"></label><div><button type="button" data-workshop-stop>Stop app</button><button type="button" data-workshop-download>Download app ↓</button><button class="workshop-run" type="button" data-workshop-run>Run app <span aria-hidden="true">↗</span></button></div></div>
 <div class="workshop-grid"><section class="workshop-source" aria-label="App source"><div class="workshop-panel-heading"><div role="tablist" aria-label="Source files"><button id="code-tab" role="tab" aria-selected="true" aria-controls="code-panel" type="button">app.js</button><button id="css-tab" role="tab" aria-selected="false" aria-controls="css-panel" tabindex="-1" type="button">style.css</button></div><span>EDITABLE / ALL OF IT</span></div><div role="tabpanel" id="code-panel" aria-labelledby="code-tab"><label class="sr-only" for="app-code">JavaScript source</label><textarea id="app-code" spellcheck="false" autocapitalize="off" autocomplete="off" maxlength="60000" aria-describedby="editor-help"></textarea></div><div role="tabpanel" id="css-panel" aria-labelledby="css-tab" hidden><label class="sr-only" for="app-css">CSS source</label><textarea id="app-css" spellcheck="false" autocapitalize="off" autocomplete="off" maxlength="20000" aria-describedby="editor-help"></textarea></div><p id="editor-help">Change a line. Run it again. <span>⌘ / Ctrl + Enter</span></p></section>
 <section class="workshop-output" aria-label="Running app"><div class="workshop-panel-heading"><span><i class="workshop-dot"></i> THE ACTUAL APP</span><span>TRY IT YOURSELF</span></div><div class="workshop-preview"><div class="workshop-waiting"><span aria-hidden="true">✳</span><p>An empty stage.<br><em>Suspicious amounts of potential.</em></p><small>Run the starter, then make it your own.</small></div></div></section></div>
 <div class="workshop-status-row"><p id="workshop-status" role="status" aria-live="polite">The stage is yours.</p><a href="#workshop-instructions" data-open-instructions>Agent instructions ↑</a></div><pre id="workshop-errors" role="alert" hidden></pre>
 <section class="workshop-next-steps" aria-labelledby="next-steps-title" hidden>
  <header><p class="eyebrow">NEXT STEPS</p><h2 id="next-steps-title">Give it a life beyond this tab.</h2></header>
  <div class="workshop-next-options">
   <section class="workshop-export" aria-labelledby="export-title"><h3 id="export-title">Keep making it yours.</h3><p>Open the code, keep tinkering, and save a link to your app.</p><button type="submit" form="codepen-form" data-workshop-codepen disabled aria-describedby="codepen-help">View on CodePen <span aria-hidden="true">↗</span></button><p id="codepen-help" class="workshop-export-help" role="status">Sends your current code to CodePen. Save it in your account to share the app. Free Pens are public.</p><form id="codepen-form" data-codepen-form action="https://codepen.io/pen/define" method="POST" target="_blank" rel="noopener noreferrer" hidden><input type="hidden" name="data"></form></section>
   <section class="workshop-share" aria-labelledby="share-title"><h3 id="share-title">Share this experience.</h3><p>Know someone who’d try this? Invite them backstage to make something with their own agent.</p><nav aria-label="Share this experience"><button type="button" data-share-copy>Copy link</button><a data-share-bluesky target="_blank" rel="noopener noreferrer">Bluesky ↗</a><a data-share-x target="_blank" rel="noopener noreferrer">X ↗</a></nav><p class="workshop-share-note">Shares the backstage experience. Your app stays yours to share from CodePen.</p><p role="status"></p><input aria-label="Backstage share link" readonly hidden></section>
  </div>
 </section>
 <footer class="workshop-footer"><span>MARIONETTE / IN YOUR BROWSER</span><p>No account. No model hiding behind the curtain.<br>Drafts stay in this tab until you reload. Download only when you want a file.</p></footer>
</dialog>`;
