export const privacy = ({ enabled = false } = {}) => ({
  title: 'Privacy & analytics — Marionette',
  description: 'What Marionette website analytics measures and how to opt out.',
  active: 'privacy',
  body: `<section class="article-heading"><p class="eyebrow">PRIVACY</p><h1>Privacy &amp;<br>analytics.</h1></section><article class="prose privacy-copy">
<h2>Website analytics</h2><p>${enabled ? 'We use PostHog to measure' : 'Our PostHog integration is prepared but is not enabled yet. When configured, it will measure'} public page views, navigation paths, time spent on pages, clicks on public links and controls, and named actions, such as opening a workshop, running a demo, copying documentation, or starting an export, using PostHog's EU service. Analytics includes page URLs (including query strings and fragments), referral sources, campaign parameters, browser, device, language and timezone information. Approximate country, region and city may be derived from the connection's IP address; we do not request precise browser location. ${enabled ? 'Session replay records' : 'When enabled, session replay will record'} page content and interactions, including demo input, editor contents and documentation search terms. PostHog protects password fields using its built-in protections. Sandboxed cross-origin app previews may not appear in recordings.</p>
<p>Analytics requests pass through our e.marionettejs.com subdomain using PostHog's managed proxy. Cloudflare processes this traffic on infrastructure that may be outside the EU; PostHog stores the analytics in its EU service.</p>
<p>PostHog uses anonymous visitor and session identifiers in a first-party cookie and browser session storage to connect page visits and recordings. The cookie expires after one day. We do not identify visitors by name or email. Test events can be excluded from reports.</p>
<p>The integration respects Global Privacy Control and Do Not Track. You can also save a choice below. Your opt-out preference is stored locally. Opting out stops new collection; requests already collected or in progress may finish. <a href="https://posthog.com/privacy">PostHog privacy policy ↗</a></p>
<button type="button" class="button" data-analytics-opt-out="true">Turn off PostHog analytics</button> <button type="button" class="button" data-analytics-opt-out="false">Clear my PostHog opt-out</button><p id="analytics-choice-status" role="status">Your choice applies in this browser to this website address. Save it separately if you use www.marionettejs.com or v5.marionettejs.com.</p>
<h2>Existing services</h2><p>Cloudflare provides hosting and its own traffic and performance analytics. Context7 Docs7 analytics is included on site pages. The optional documentation chat sends messages you submit to Context7 to answer your questions; these messages are separate from PostHog analytics. The controls above apply to PostHog only.</p><p><a href="https://www.cloudflare.com/privacypolicy/">Cloudflare privacy policy ↗</a> · <a href="https://context7.com/privacy">Context7 privacy policy ↗</a></p>
</article>`
});
