import { adoptionInvitation } from './adoption.mjs';
import provenance from './provenance.json' with { type: 'json' };

export const why = {
  title:'Why Marionette 5? Your agent learns the library. You direct the application.',
  description:'Evaluate Marionette for agent-led development: clear responsibilities, readable code, available integrations, and a practical first feature.',
  active:'why',
  body:`
<section class="article-heading why-heading"><p class="eyebrow">WHY MARIONETTE / A WORKING ARRANGEMENT</p><h1>Your agent has<br><em>some reading to do.</em></h1><p>You have an application to build. Marionette gives your agent patterns to work with—and leaves you with code you can follow.</p></section>
${adoptionInvitation}
<div class="article-layout"><aside class="article-nav" aria-label="On this page"><p class="eyebrow">ON THIS PAGE</p><a href="#agents">Who learns what</a><a href="#fit">Where it fits</a><a href="#integrations">What comes with it</a><a href="#release">About the release candidate</a><a href="#evidence">Try the moving parts</a><a href="#next-step">Ask for a change</a></aside>
<article class="prose">
<section id="agents"><p class="eyebrow">01 / YOU CAN SKIP THE FLASH CARDS</p><h2>Know your application.<br>Let the agent learn the APIs.</h2><p>You should be able to ask for a searchable list, open an editor, or change what happens after saving without memorizing the framework first. Your agent can read the contracts and choose the implementation.</p>
<dl class="working-agreement"><div><dt>You direct.</dt><dd>Describe the behavior. Try the result. Decide what needs to change. Read the relevant code when you want a closer look.</dd></div><div><dt>Your agent implements.</dt><dd>Find the matching documentation. Choose the responsible Application or View. Make the change, then check that it behaves as requested.</dd></div></dl>
<p>Marionette gives that work a recognizable shape. A Region owns the View in one part of a screen. A CollectionView manages repeated items. An Application gives a feature a start and a stop. The agent has a vocabulary for building it; you have a way to follow what it built.</p><p>The agent will still have ideas. Some of them will even be good. Clear responsibilities give you somewhere to point when the next instruction is “change this part.”</p><a class="text-link" href="/docs/agent-start/">Give your agent its reading →</a></section>
<section id="fit"><p class="eyebrow">02 / CHOOSE IT FOR THE WORK</p><h2>For applications with<br>moving parts.</h2><p>A list that stays put while its detail panel changes. An editor with local state. A feature that loads data before opening and cleans up when it closes. These are the kinds of relationships Marionette makes explicit.</p><p>That structure is useful when an agent will keep adding and revising features—and someone needs to understand where each change belongs.</p><p>A mostly static page or a small isolated interaction may need very little of it. If your product depends on a particular component library, server-rendering setup, or framework-specific integration, have the agent verify that fit before choosing Marionette.</p><p>For an existing application, begin with the problem you want to solve. Keeping the current stack, introducing one isolated feature, and migrating are different decisions. A new version is not a reason to rewrite a working application.</p></section>
<section id="integrations"><p class="eyebrow">03 / WHAT’S IN THE BOX</p><h2>A familiar name.<br>A different set of choices.</h2><p>Marionette 5 no longer requires Backbone, jQuery, or Underscore in core. Plain objects, static arrays, and native DOM operations are available from the start.</p>
<dl class="integration-ledger"><div><dt>Interface structure</dt><dd>Applications, Views, Regions, CollectionViews, and Behaviors organize the feature and its lifetime. <a href="/docs/architecture/">See how they fit.</a></dd></div><div><dt>Rendering &amp; DOM</dt><dd>Template functions work with the default renderer. Optional adapters connect Lit HTML, Morphdom, or jQuery; a renderer API supports other template systems. <a href="/docs/packages/adapters/">Check the available adapters.</a></dd></div><div><dt>Data &amp; state</dt><dd>Optional <code>@mnjs/data</code> provides observable Models and Collections. Adapters also connect Backbone sources and XState actors. <a href="/docs/integrations/setup/">Choose the data setup.</a></dd></div><div><dt>Your application</dt><dd>You supply API access and persistence, choose components and routing, and connect the tools your product needs. Check each required integration; an extension point still needs an implementation.</dd></div></dl>
<p>If you know an earlier Marionette, send your agent to the <a href="/docs/guides/migration/">v5 migration guide</a>. It has a few habits to unlearn.</p></section>
<section id="release"><p class="eyebrow">04 / THE VERSION MATTERS</p><h2>Available to evaluate.<br>Still a release candidate.</h2><p>This site’s documentation and demos use <strong>Marionette ${provenance.packageVersion}</strong>. Pin matching package versions and decide whether a prerelease fits your project’s delivery requirements.</p><p>Before committing a product, check the integrations and support you will depend on. Agent-readable guidance helps with implementation; maintainer availability and the people who will own the application still belong in the decision.</p><a class="text-link" href="/docs/quick-start/#install-the-release-candidate">See the installation requirements →</a></section>
<section id="evidence"><p class="eyebrow">05 / PULL SOMETHING</p><h2>Try the moving parts.</h2><p>Choose an item in the <a href="/#demo">homepage application</a>. Its detail View is replaced and the previous one is destroyed. The screen and list keep their identities. Follow that small change before asking your agent for a bigger one.</p><p>The <a href="/demos/">demos</a> put lists, cleanup, and unfinished work on display, with their running source alongside. Radio Ghostbusters is about cleanup. The ghosts are there to help.</p><p>For a more ordinary feature, give your agent the <a href="/docs/records/">Records example</a>: loading, selection, retry, and keeping the interface in place. Then bring a request of your own to <a href="/#playground">Backstage</a>.</p><p>For a complete application, read the <a href="/case-studies/realworld/">RealWorld case study</a>: three development stages, the resulting Conduit frontend, and measured comparisons with selected implementations.</p></section>
<section id="next-step"><p class="eyebrow">06 / THE SECOND REQUEST IS THE INTERESTING ONE</p><h2>Build a feature.<br>Then change your mind.</h2><ol class="evaluation-sequence"><li><strong>Ask for something useful.</strong><p>Choose one feature with an interaction and a data or state change. Give your agent the <a href="/docs/agent-start/">agent entrypoint</a> and your requirements.</p></li><li><strong>Ask for a revision.</strong><p>Change the selection behavior, add a filter, or adjust what happens after saving. Ask the agent to explain which part owns the change.</p></li><li><strong>Try both paths.</strong><p>Check the new behavior and the behavior you expected to keep. Close and reopen the feature. Follow the changed code far enough to decide whether you can keep directing it.</p></li></ol><p>You do not need to recite the API. You need an application you can work on with your agent—and a second change that still makes sense.</p><a class="button" href="/#playground">Bring your agent to Backstage <span aria-hidden="true">→</span></a></section>
</article></div>`
};
